### PR TITLE
Expose range deletions to table property collectors

### PR DESCRIPTION
**Pull request by petermattis**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/rocksdb/19)

### CODE REVIEW

**Comment by petermattis** [comment]
@benesch This was originally your commit. I'm going to try to push the delete range property collector over the line.

**Review by benesch — APPROVED** [review]
Ack. FYI this was implemented upstream by someone else with (IIRC) a slightly different constant name. You might want to backported that implementation instead.

**Comment by petermattis** [comment]
Ok. Let me go track that down instead.

**Comment by petermattis** [comment]
Done. PTAL.

**Review by benesch — APPROVED** [review]

**Pull request merged**
