### PR TITLE
db_impl_open: Error out if WAL replay seqnums aren't increasing

### PR DESCRIPTION
**Pull request by itsbilal**
This should help trip early on issues such as the one found in:
https://github.com/cockroachdb/pebble/issues/567

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/rocksdb/78)

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/rocksdb/78)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @itsbilal, @petermattis, and @sumeerbhola)

___
*[db/db_impl_open.cc, line 767 at r1](https://reviewable.io/reviews/cockroachdb/rocksdb/78#-M2k3fHq13MIcWB8nBjQ:-M2k3fHrCLg0gxUos7hJ:b-nekc4z) ([raw file](https://github.com/cockroachdb/rocksdb/blob/6c8c391582f67e1293cbef9b35add4340c4a330e/db/db_impl_open.cc#L767)):*
> ```cpp
>       // That's why we set ignore missing column families to true
>       bool has_valid_writes = false;
>       if (last_observed_seq > sequence) {
> ```

I think `next_sequence` holds the next expected sequence number. Can this conditional be something like:

```
if (*next_sequence != kMaxSequenceNumber && sequence < *next_sequence) {
  ...
}
```

The benefit to this (besides getting rid of `last_observed_seq`) is it looks like `next_sequence` is kept up to date across log files. It also accounts for the sequence number increase from the entries in a batch.
___
*[db/db_impl_open.cc, line 769 at r1](https://reviewable.io/reviews/cockroachdb/rocksdb/78#-M2k3zr-C07_BKIpV0HJ:-M2k3zr-C07_BKIpV0HK:bvvlxcw) ([raw file](https://github.com/cockroachdb/rocksdb/blob/6c8c391582f67e1293cbef9b35add4340c4a330e/db/db_impl_open.cc#L769)):*
> ```cpp
>       if (last_observed_seq > sequence) {
>         status = Status::Corruption(
>           "Sequence numbers in WAL not in increasing order");
> ```

I think you can pass in arguments here. It would be nice to include the batch sequence number and the previous sequence number.

**Review by itsbilal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/rocksdb/78)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @petermattis and @sumeerbhola)

___
*[db/db_impl_open.cc, line 767 at r1](https://reviewable.io/reviews/cockroachdb/rocksdb/78#-M2k3fHq13MIcWB8nBjQ:-M2nX3PK9vrWk1r-LH5H:b-unf66w) ([raw file](https://github.com/cockroachdb/rocksdb/blob/6c8c391582f67e1293cbef9b35add4340c4a330e/db/db_impl_open.cc#L767)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think `next_sequence` holds the next expected sequence number. Can this conditional be something like:

```
if (*next_sequence != kMaxSequenceNumber && sequence < *next_sequence) {
  ...
}
```

The benefit to this (besides getting rid of `last_observed_seq`) is it looks like `next_sequence` is kept up to date across log files. It also accounts for the sequence number increase from the entries in a batch.
</blockquote></details>

Good point. Made the change.
___
*[db/db_impl_open.cc, line 769 at r1](https://reviewable.io/reviews/cockroachdb/rocksdb/78#-M2k3zr-C07_BKIpV0HJ:-M2nX7BBD846XRZ4b-d0:b-wzw5ui) ([raw file](https://github.com/cockroachdb/rocksdb/blob/6c8c391582f67e1293cbef9b35add4340c4a330e/db/db_impl_open.cc#L769)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think you can pass in arguments here. It would be nice to include the batch sequence number and the previous sequence number.
</blockquote></details>

`Corruption` only takes 2 args at most, including the first message, so I just did the same approach as elsewhere and converted the two sequence numbers into strings and concatenated them.

**Review by petermattis — APPROVED** [review]
:lgtm:

I feel we should make a similar change to this in Pebble. The protection seems worthwhile.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/rocksdb/78#-:-M2njXAy6ZUKAejVTJaS:b-a3q66l)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @sumeerbhola)

**Comment by itsbilal** [comment]
TFTR! Non-java tests are passing

**Pull request merged**
