### PR TITLE
Properly handle range tombstones at the same seqnum as a key

### PR DESCRIPTION
**Pull request by petermattis**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/rocksdb/10)

### CODE REVIEW

**Comment by tbg** [comment]
Does this fix a bug? A little detail would be nice.

**Comment by petermattis** [comment]
The handling of range tombstones at the same seqnum is necessary to properly handle range tombstones in ingested sstables. So not a bug at the moment, but it would have been one in the future.

The `LessOfComparator` buglet was definitely a bug, though I'm not sure if it affected us. I stumbled across it when I wrote a test upstream which used `ReverseBytewiseComparator`.

**Comment by tbg** [comment]
LGTM

The LessOfComparator buglet would've resulted in a crash, right?

**Review by benesch — APPROVED** [review]
Sorry, somehow missed this was on my plate.  LGTM.

**Comment by petermattis** [comment]
> The LessOfComparator buglet would've resulted in a crash, right?

Yes.

**Pull request merged**
