### PR TITLE
Revert snap_refresh_nanos feature (#5269)

### PR DESCRIPTION
**Pull request by ajkr**
Summary:
Our daily stress tests are failing after this feature. Reverting temporarily until we figure the reason for test failures.
Pull Request resolved: https://github.com/facebook/rocksdb/pull/5269

Differential Revision: D15151285

Pulled By: maysamyabandeh

fbshipit-source-id: e4002b99690a97df30d4b4b58bf0f61e9591bc6e

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/rocksdb/56)

### CODE REVIEW

**Comment by ajkr** [comment]
running a bunch of repro attempts, will report whether any inconsistencies are found.

**Review by petermattis — APPROVED** [review]
This was a clean backport of the revert, right?

**Comment by ajkr** [comment]
Right. Trying to remember to write that before you ask. Next time...

**Comment by petermattis** [comment]
Ack. I’m just being overly cautious this late in the release cycle.

**Comment by ajkr** [comment]
OK on cockroach master with this patch import seems to work:
```
I190918 21:29:13.566949 1 ccl/workloadccl/fixture.go:327  imported 77 GiB bytes in 9 tables (took 26m27.015068046s, 49.76 MiB/s)
```

**Comment by ajkr** [comment]
the test failures are unrelated (timeouts downloading dependencies).

**Pull request merged**
