### PR TITLE
range deletion performance improvements + cleanup

### PR DESCRIPTION
**Pull request by benesch**
Upstream PR: facebook/rocksdb#4014. See individual commits for details.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/rocksdb/5)

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
:lgtm:

Did anything significant change from the upstream PR (which I already reviewed)? 

> Reviewed 6 of 6 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/rocksdb/5#-:-LH4SPar0OjfTK9XuvU7:b-m7e61c)* status: 2 of 10 files reviewed, all discussions resolved (waiting on @petermattis and @bdarnell)

**Review by benesch — COMMENTED** [review]
Nope. I replaced an `it++` with a `++it`.  Everything else was just resolving rebase conflicts.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/rocksdb/5#-:-LH4T6Wb9QW-zIrCIAyX:bk2ff77)* status: 2 of 10 files reviewed, all discussions resolved (waiting on @petermattis and @bdarnell)

**Review by bdarnell — APPROVED** [review]
The PR title mentions performance improvements, but it's not clear from the individual commit messages where the performance improvement could come from (it's laying the groundwork for truncating the tombstones, but not doing it yet). Is it just that the new split implementation is more efficient than the hybrid multimap version?

> Reviewed 6 of 6 files at r1, 1 of 1 files at r2, 4 of 4 files at r3, 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/rocksdb/5#-:-LH4frVWE_EIa87BXYur:br0g0fp)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by benesch** [comment]
Yeah, the cleanup in "Split collapsed and uncollapsed tombstone map representations" (bd83fd0) refactors the collapsed AddTombstone function in a way that resolves a performance bug. The bug is more precisely explained in https://github.com/facebook/rocksdb/pull/3992.

I think I originally had a commit that more precisely described what was going on, but it got amended into bd83fd0 and is never coming back. I can make bd83fd0's commit message better, though.

**Comment by benesch** [comment]
This just went through a round of upstream review, so I'm going to hold off on merging this for another few days to see if it lands there. 🤞

**Comment by petermattis** [comment]
@benesch Ack. Do you want me to take care of the merge conflicts here?

**Comment by benesch** [comment]
I'm happy to take care of them, but if you're itching to get this in, by
all means go for it! The upstream patch has been updated to address some of
Andrew's feedback, so it may be easier to redo the rebase from scratch.

**Comment by petermattis** [comment]
Superseded by #8.

**Pull request closed without merging**
