### PR TITLE
Support range deletion tombstones in IngestExternalFile SSTs

### PR DESCRIPTION
**Pull request by nvb**
First commit: facebook/rocksdb#4016.
Upstream PR: facebook/rocksdb#3778.

This change adds a `DeleteRange` method to `SstFileWriter` and adds
support for ingesting SSTs with range deletion tombstones. This is
important for applications that need to atomically ingest SSTs while
clearing out any existing keys in a given key range.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/rocksdb/7)

### CODE REVIEW

**Comment by nvb** [comment]
This doesn't need a review immediately. Mainly publishing for CI. We can review in-depth once we're comfortable enough with range deletion tombstones to write multiple on every Range snapshot.

**Review by benesch — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/rocksdb/7)* status: all files reviewed, 6 unresolved discussions (waiting on @nvanbenschoten)

___
*[USERS.md, line 29 at r1](https://reviewable.io/reviews/cockroachdb/rocksdb/7#-LH5F4e039sWWzC3NhWN:-LH5F4e16TVAnwRCt4hK:bnobdns) ([raw file](https://github.com/cockroachdb/rocksdb/blob/d43a96c92cb519abadc7810c3e106e80ab3eaf1a/USERS.md#L29)):*
> ```Markdown
> 
> ## CockroachDB
> CockroachDB is an open-source geo-replicated transactional database. They are using RocksDB as their storage engine. Check out their github: https://github.com/cockroachdb/cockroach
> ```

This is by far the most important change in this PR.
___
*[db/external_sst_file_basic_test.cc, line 119 at r1](https://reviewable.io/reviews/cockroachdb/rocksdb/7#-LH5koPq3bgpjGoT0l15:-LH5koPq3bgpjGoT0l16:b-qq8tif) ([raw file](https://github.com/cockroachdb/rocksdb/blob/d43a96c92cb519abadc7810c3e106e80ab3eaf1a/db/external_sst_file_basic_test.cc#L119)):*
> ```cpp
>     return GenerateAndAddExternalFile(options, keys, value_types, {}, file_id,
>                                       true_data);
>   }
> ```

I kind of love overloading. It's so nice not to have to methods like `WithRangeDeletionsWithFooBazOptionWithCar` everywhere.
___
*[db/external_sst_file_basic_test.cc, line 394 at r1](https://reviewable.io/reviews/cockroachdb/rocksdb/7#-LH5lKyP3ctWHrlHIUVk:-LH5l6ij8FJZx5q2DDtk:b5cugld) ([raw file](https://github.com/cockroachdb/rocksdb/blob/d43a96c92cb519abadc7810c3e106e80ab3eaf1a/db/external_sst_file_basic_test.cc#L394)):*
> ```cpp
>     // The range deletion ends on a key, but it doesn't actually delete
>     // this key because the largest key in the range is exclusive. Still,
>     // if counts as an overlap so a new seqno will be assigned.
> ```

"it"

also, does it really end on a key? You don't seem to be generating any keys in this SST.
___
*[db/external_sst_file_basic_test.cc, line 394 at r1](https://reviewable.io/reviews/cockroachdb/rocksdb/7#-LH5mwHN3XIMBi2jYjWb:-LH5mwHN3XIMBi2jYjWc:bz8jatv) ([raw file](https://github.com/cockroachdb/rocksdb/blob/d43a96c92cb519abadc7810c3e106e80ab3eaf1a/db/external_sst_file_basic_test.cc#L394)):*
> ```cpp
>     // The range deletion ends on a key, but it doesn't actually delete
>     // this key because the largest key in the range is exclusive. Still,
>     // if counts as an overlap so a new seqno will be assigned.
> ```

Would using `sstableKeyCompare` from #4 allow us to lift this restriction?
___
*[db/external_sst_file_basic_test.cc, line 399 at r1](https://reviewable.io/reviews/cockroachdb/rocksdb/7#-LH5lHZ8-QKpZ_xLK6e8:-LH5lHZ8-QKpZ_xLK6e9:bbbi892) ([raw file](https://github.com/cockroachdb/rocksdb/blob/d43a96c92cb519abadc7810c3e106e80ab3eaf1a/db/external_sst_file_basic_test.cc#L399)):*
> ```cpp
>     ASSERT_OK(GenerateAndAddExternalFile(options, {}, {}, {{100, 109}},
>                                          file_id++, &true_data));
>     // File dont overwrite any keys, No seqno needed
> ```

I appreciate that you're consistent with the comments above, but... ugh!
___
*[db/external_sst_file_test.cc, line 639 at r1](https://reviewable.io/reviews/cockroachdb/rocksdb/7#-LH5mnSR92fIdWIVhDxi:-LH5mnSR92fIdWIVhDxj:b-7esevx) ([raw file](https://github.com/cockroachdb/rocksdb/blob/d43a96c92cb519abadc7810c3e106e80ab3eaf1a/db/external_sst_file_test.cc#L639)):*
> ```cpp
>     // Both of the following overlap on the end key of a range deletion
>     // tombstone. This is a limitation because these tombstones have exclusive
>     // end keys that should not count as overlapping with other keys.
> ```

Ditto here.
___
*[table/block_based_table_reader.cc, line 831 at r1](https://reviewable.io/reviews/cockroachdb/rocksdb/7#-LH5k2qS6CVYgoZ2JtIG:-LH5k2qTD55Yhz-a4jbR:bsthbof) ([raw file](https://github.com/cockroachdb/rocksdb/blob/d43a96c92cb519abadc7810c3e106e80ab3eaf1a/table/block_based_table_reader.cc#L831)):*
> ```cpp
>                                                 rep->ioptions.info_log);
>   }
> ```

Why did this have to move, out of curiosity?

**Review by bdarnell — COMMENTED** [review]
> Reviewed 7 of 19 files at r3, 11 of 11 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/rocksdb/7)* status: all files reviewed, 7 unresolved discussions (waiting on @nvanbenschoten)

___
*[db/external_sst_file_ingestion_job.cc, line 382 at r5](https://reviewable.io/reviews/cockroachdb/rocksdb/7#-LH9YeRR5opKBD-kcMrb:-LH9YeRS0-_HruADfhUo:b-77j8cd) ([raw file](https://github.com/cockroachdb/rocksdb/blob/6180d31e21b4c1bd331d084280b639b9d29cd680/db/external_sst_file_ingestion_job.cc#L382)):*
> ```cpp
>   }
> 
>   // We may need to adjust these key bounds, depending on whether any range
> ```

In #3, we clip tombstones to sstable bounds. Do we still need to expand the sst bounds for oversized tombstones here?

**Review by nvb — COMMENTED** [review]
@benesch yes, I included facebook/rocksdb#4016 as the first commit here. 

Thanks for looking this over. Since it looks like https://github.com/facebook/rocksdb/pull/3778 may actually make some movement soon, I'm going to let this sit. I did update the upstream PR with the changes suggested here though.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/rocksdb/7#-:-LHBYdlcBhSLXJoHzHYu:b-nzmqyu)* status: all files reviewed, 7 unresolved discussions (waiting on @nvanbenschoten and @benesch)

___
*[USERS.md, line 29 at r1](https://reviewable.io/reviews/cockroachdb/rocksdb/7#-LH5F4e039sWWzC3NhWN:-LHAzzYQC9DyyPM1uzWf:bb9o07r) ([raw file](https://github.com/cockroachdb/rocksdb/blob/d43a96c92cb519abadc7810c3e106e80ab3eaf1a/USERS.md#L29)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

This is by far the most important change in this PR.
</blockquote></details>

It made me uncomfortable to be relying on a project with such a glaring bug in it.
___
*[db/external_sst_file_basic_test.cc, line 394 at r1](https://reviewable.io/reviews/cockroachdb/rocksdb/7#-LH5lKyP3ctWHrlHIUVk:-LHBQ4AQ9JH71a-CMM-s:bptw0rh) ([raw file](https://github.com/cockroachdb/rocksdb/blob/d43a96c92cb519abadc7810c3e106e80ab3eaf1a/db/external_sst_file_basic_test.cc#L394)):*
Done.

> does it really end on a key

The key is in the previous sst.
___
*[db/external_sst_file_basic_test.cc, line 394 at r1](https://reviewable.io/reviews/cockroachdb/rocksdb/7#-LH5mwHN3XIMBi2jYjWb:-LHBXV0h8zmUuJD1CH6d:b-ox6gbz) ([raw file](https://github.com/cockroachdb/rocksdb/blob/d43a96c92cb519abadc7810c3e106e80ab3eaf1a/db/external_sst_file_basic_test.cc#L394)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Would using `sstableKeyCompare` from #4 allow us to lift this restriction?
</blockquote></details>

Yeah, it looks like that's addressing the exact same issue. I'll explore what it would take to lift the restriction using `sstableKeyCompare`.
___
*[db/external_sst_file_basic_test.cc, line 399 at r1](https://reviewable.io/reviews/cockroachdb/rocksdb/7#-LH5lHZ8-QKpZ_xLK6e8:-LHB-_-3CRVhORk8LTNc:b6egg3v) ([raw file](https://github.com/cockroachdb/rocksdb/blob/d43a96c92cb519abadc7810c3e106e80ab3eaf1a/db/external_sst_file_basic_test.cc#L399)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

I appreciate that you're consistent with the comments above, but... ugh!
</blockquote></details>

Consistency before all else!

Fixed in https://github.com/facebook/rocksdb/pull/3778/commits/c10eb46c1bb99f76bb1043808c4ddeb0953da277.
___
*[db/external_sst_file_ingestion_job.cc, line 382 at r5](https://reviewable.io/reviews/cockroachdb/rocksdb/7#-LH9YeRR5opKBD-kcMrb:-LHBQgqA-qUfMxP2APOe:b-8g3hny) ([raw file](https://github.com/cockroachdb/rocksdb/blob/6180d31e21b4c1bd331d084280b639b9d29cd680/db/external_sst_file_ingestion_job.cc#L382)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

In #3, we clip tombstones to sstable bounds. Do we still need to expand the sst bounds for oversized tombstones here?
</blockquote></details>

This isn't setting the sstable bounds, it's determining what the largest user key is so that we know the lowest level that we can ingest the sst into. I don't _think_ #3 affects this.
___
*[table/block_based_table_reader.cc, line 831 at r1](https://reviewable.io/reviews/cockroachdb/rocksdb/7#-LH5k2qS6CVYgoZ2JtIG:-LHBQKQr4ZtQ-GFxQKky:b15t0em) ([raw file](https://github.com/cockroachdb/rocksdb/blob/d43a96c92cb519abadc7810c3e106e80ab3eaf1a/table/block_based_table_reader.cc#L831)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Why did this have to move, out of curiosity?
</blockquote></details>

We needed to read the global sequence number before reading the range deletion meta block.

**Review by petermattis — CHANGES_REQUESTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/rocksdb/7#-:-LHE1EpM9QX8x2sh7wOb:bnfp4nl)* status: all files reviewed, 13 unresolved discussions (waiting on @benesch, @bdarnell, and @nvanbenschoten)

___
*[db/external_sst_file_ingestion_job.cc, line 74 at r5](https://reviewable.io/reviews/cockroachdb/rocksdb/7#-LHE0yil7xH7LeMNJiZf:-LHE0yil7xH7LeMNJiZg:b-vzsp19) ([raw file](https://github.com/cockroachdb/rocksdb/blob/6180d31e21b4c1bd331d084280b639b9d29cd680/db/external_sst_file_ingestion_job.cc#L74)):*
> ```cpp
>     for (size_t i = 0; i < num_files - 1; i++) {
>       if (ucmp->Compare(sorted_files[i]->largest_user_key,
>                         sorted_files[i + 1]->smallest_user_key) >= 0) {
> ```

This should probably be using `sstableKeyCompare`. Not a big deal, it just means we'll reject certain ingestions unnecessarily.
___
*[db/external_sst_file_ingestion_job.cc, line 387 at r5](https://reviewable.io/reviews/cockroachdb/rocksdb/7#-LHE0UaaCRvbgKZwX0N8:-LHE0UaaCRvbgKZwX0N9:b744396) ([raw file](https://github.com/cockroachdb/rocksdb/blob/6180d31e21b4c1bd331d084280b639b9d29cd680/db/external_sst_file_ingestion_job.cc#L387)):*
> ```cpp
>   if (range_del_iter != nullptr) {
>     range_del_iter->SeekToFirst();
>     if (range_del_iter->Valid()) {
> ```

Is there a reason for this extra call to `Valid()`? The normal iterator pattern is:

```
for (range_del_iter->SeekToFirst(); range_del_iter->Valid(); range_del_iter->Next()) {
...
}
```
___
*[db/external_sst_file_ingestion_job.cc, line 402 at r5](https://reviewable.io/reviews/cockroachdb/rocksdb/7#-LHE-pYXDwmKR4PtCkbQ:-LHE-pYXDwmKR4PtCkbR:b-mvv141) ([raw file](https://github.com/cockroachdb/rocksdb/blob/6180d31e21b4c1bd331d084280b639b9d29cd680/db/external_sst_file_ingestion_job.cc#L402)):*
> ```cpp
>             ucmp->Compare(tombstone.end_key_,
>                           file_to_ingest->largest_user_key) > 0) {
>           file_to_ingest->largest_user_key = tombstone.end_key_.ToString();
> ```

Because `tombstone.end_key_` is exclusive, this isn't quite correct, though I'm not sure if it is a problem. I believe it simply means we will ingest the sstable at a higher level than necessary. Might be worth a comment explaining that. 
___
*[db/range_del_aggregator.cc, line 215 at r5](https://reviewable.io/reviews/cockroachdb/rocksdb/7#-LHDzH0XDjxLuhH1sPMF:-LHDzH0XDjxLuhH1sPMG:b-1vub78) ([raw file](https://github.com/cockroachdb/rocksdb/blob/6180d31e21b4c1bd331d084280b639b9d29cd680/db/range_del_aggregator.cc#L215)):*
> ```cpp
>       rep_->pinned_slices_.emplace_back(input->key().data(), input->key().size());
>       parsed = ParseInternalKey(rep_->pinned_slices_.back(), &parsed_key);
>     }
> ```

Nit: Feels weird to call `ParseInternalKey` in both code paths. I would have structured the above as:

```
rocksdb::Slice key = input->key();
if (!input->IsKeyPinned()) {
  // The tombstone map holds slices into the iterator's memory. Make a
  // copy of the key if it is not pinned.
  rep_->pinned_slices_.emplace_back(key.data(), key.size());
  key = rep_->pinned_slices_.back();
}
ParsedInternalKey parsed_key;
if (!ParseInternalKey(key, &parsed_key)) {
  ...
}
```
___
*[include/rocksdb/sst_file_writer.h, line 63 at r5](https://reviewable.io/reviews/cockroachdb/rocksdb/7#-LHDzwF7BamG_HrthhHH:-LHDzwF8AtrsM74ZdI2W:b8en72d) ([raw file](https://github.com/cockroachdb/rocksdb/blob/6180d31e21b4c1bd331d084280b639b9d29cd680/include/rocksdb/sst_file_writer.h#L63)):*
> ```objc
>   std::string largest_key;   // largest user key in file
>   std::string
>       smallest_range_del_key;  // smallest range deletion user key in file
> ```

Why is `smallest_range_del_key` on a newline? 
___
*[include/rocksdb/sst_file_writer.h, line 119 at r5](https://reviewable.io/reviews/cockroachdb/rocksdb/7#-LHE1rvP1UQKc1ul1pW5:-LHE1rvP1UQKc1ul1pW6:b707bh1) ([raw file](https://github.com/cockroachdb/rocksdb/blob/6180d31e21b4c1bd331d084280b639b9d29cd680/include/rocksdb/sst_file_writer.h#L119)):*
> ```objc
>   Status Delete(const Slice& user_key);
> 
>   // Add a range deletion tombstone to currently opened file
> ```

The semantics of this are a bit unusual. If the sstable is later ingested, the range deletion tombstone will not apply to any of the keys in the sstable, but only to already existing keys in the DB. Might be worth calling this out in a comment.

**Comment by petermattis** [comment]
@nvanbenschoten Are you going to take care of the merge conflicts here? Do you want me to take over this PR and re-do the cherry-pick from the upstream PR?

**Comment by nvb** [comment]
> Are you going to take care of the merge conflicts here

Yes, I was going to take care of it. The only complication is that https://github.com/cockroachdb/rocksdb/pull/4 was merged here but hasn't been merged upstream yet, so there might be a bit of skew. Shouldn't be too bad though.

**Comment by benesch** [comment]
Ping! Is this still in your queue, @nvanbenschoten?

**Comment by nvb** [comment]
Closing because we're not planning on getting streaming snapshots into 2.1 anymore. This has landed upstream so we'll pick it up when we bump to 5.15.

**Pull request closed without merging**
